
#ifndef __dealii_qc_dipole_potential_field_h
#define __dealii_qc_dipole_potential_field_h

#include <deal.II-qc/potentials/potential_field.h>


DEAL_II_QC_NAMESPACE_OPEN


/**
 * Class for describing potential generated by a dipole in a
 * <tt>spacedim</tt>-dimensional space.
 *
 * The electrostatic potential energy of a charged particle, at a location
 * \f$\boldsymbol{\mathsf x}\f$ and charge \f$q\f$, due to presence of a dipole
 * at a location \f$ \boldsymbol{\mathsf d} \f$ is given by
 * \f[
 *      \phi(\boldsymbol{\mathsf x}) = \frac{q}{4\pi\epsilon_0}
 *              \frac{\boldsymbol{\mathsf \mu} \cdot\boldsymbol {\mathsf r}}
 *              {|\boldsymbol{\mathsf r}|^3},
 * \f]
 * where \f$ \boldsymbol {\mathsf r}= \boldsymbol{\mathsf d} -
 * \boldsymbol{\mathsf x}\f$ and
 * \f$ \boldsymbol{\mathsf \mu} \f$ is the electric dipole moment of the dipole.
 *
 * The gradient of the electrostatic potential energy is given as
 * \f[
 *      \nabla  \phi(\boldsymbol{\mathsf x}) =
 *
 *      \frac{q}{4\pi\epsilon_0}
 *      \frac{1}{|\boldsymbol{\mathsf r}|^3}
 *      \Big[
 *            \boldsymbol{\mathsf \mu}
 *            -
 *            3
 *            \big[
 *                  \boldsymbol{\mathsf \mu} \cdot
 *                  \boldsymbol{\widehat{\mathsf r}}
 *            \big]
 *            \boldsymbol{\widehat{\mathsf r}}
 *      \Big].
 * \f]
 */
template <int spacedim>
class DipolePotentialField : public PotentialField<spacedim>
{
public:
  /**
   * Constructor takes in @p dipole_location, @p dipole_orientation,
   * @p dipole moment of the dipole, and
   * @p initial_time that defaults to zero.
   */
  DipolePotentialField(const Point<spacedim> &    dipole_location,
                       const Tensor<1, spacedim> &dipole_orientation,
                       const double               dipole_moment,
                       const double               initial_time = 0.);

  /**
   * Return the potential energy of a charged particle,
   * located at @p p and with charge @p q, due to the presence of dipole.
   */
  double
  value(const Point<spacedim> &p, const double q) const;

  /**
   * Return the gradient of the potential energy of a charged particle,
   * located at @p p and with charge @p q, due to the presence of dipole.
   */
  Tensor<1, spacedim>
  gradient(const Point<spacedim> &p, const double q) const;

protected:
  // Allow all dipole properties to change with time.

  /**
   * Location of the dipole in <tt>spacedim</tt>-dimensional space.
   */
  Point<spacedim> dipole_location;

  /**
   * Orientation of the dipole.
   */
  Tensor<1, spacedim> dipole_orientation;

  /**
   * Magnitude of the dipole_moment of the dipole.
   */
  double dipole_moment;
};


DEAL_II_QC_NAMESPACE_CLOSE

#endif /* __dealii_qc_dipole_potential_field_h */
